name: Auto Commit Demo

on:
  schedule:
    - cron: "0 0 * * *"   # runs every day
  workflow_dispatch:

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Create file
        run: |
          echo "Hello from GitHub Actions" > auto.txt

      - name: Commit file
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Auto update file"
          git push
