name: Test Metrics

on:
  workflow_dispatch:   # manual test only

permissions:
  contents: write

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate metrics.svg minimal
        uses: lowlighter/metrics@v1.0.7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: alphonsasooter
          template: classic
          base: header
          output_file: metrics.svg